name: Landing Page CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: Tests
        run: yarn test
